const { buildConstructionSummary } = require('../core/buildSummary.cjs');
const { buildTraceFromChanges } = require('../core/explainTrace.cjs');

function renderEvent(e){ return e.text || `${e.type}`; }
function offerText(o){ return `${o.name}${o.frozen?'[冻]':''}(${o.price})${o.restock?.name?`[补货:${o.restock.name}]`:''}`; }
function inventoryText(i){ return `${i.petId}x${i.count || 1}(Lv${i.level || 1})${i.acquiredFrom?.name?`[来源:${i.acquiredFrom.name}]`:''}`; }
function renderPlayerReport(state){ const lines=[]; const counts={pets:state.data.pets.length,monsters:state.data.monsters.length,waves:state.data.waves.length,mechanisms:state.data.mechanisms.length,events:state.data.events.length,shop:state.data.shop.length,relics:state.data.relics.length,shapes:state.data.shapes.length};
 lines.push('《元素背包史》全数据纯文字流程报告'); lines.push(`数据：${counts.pets}宠 / ${counts.monsters}怪物模板 / ${counts.waves}波次 / ${counts.mechanisms}机制 / ${counts.events}事件 / ${counts.shop}商店商品 / ${counts.relics}遗物祝福 / ${counts.shapes}形状槽。`); lines.push(`场次：第${state.day}天${state.period}，节点路线→中午遭遇→晚上固定战，全程不接UI。`); lines.push(''); lines.push('【玩家操作行为】');
 for(const e of state.events){ if(['NODE_OPTIONS','NODE_PICK','NODE_EVENT_APPLY','NODE_REST','BATTLE_OPTIONS','BATTLE_PICK','FIXED_BATTLE_START','ROUTE_POST_BATTLE_EVENT_APPLY','ROUTE_BATTLE_OUTCOME','ROUTE_REWARD_CLAIM','DAY_ROUTE_END','RUN_TERMINAL','OUTER_RUN_EFFECT_QUEUE','OUTER_RUN_EFFECT_CONSUME','CONSTRUCTION_EVENT_APPLY','CONSTRUCTION_EVENT_BLOCKED','BATTLE_START','BATTLE_PREP_EFFECT_QUEUE','BATTLE_PREP_EFFECT_APPLY','FIRE_TRAP_TRIGGER','ROUND_START','SPAWN_ENEMY','PLAYER_SELECT_SLOT','APPLY_ELEMENT','PLAYER_TURN_END','ELEMENT_SETTLE','DAMAGE','UNIT_DEAD','MONSTER_INTENT','BATTLE_END','REWARD_OPTIONS','REWARD_PICK','SHOP_ENTER','SHOP_ROLL','SHOP_TARGETED_RESTOCK','SHOP_FREEZE','SHOP_UNFREEZE','SHOP_BUY','SHOP_EVENT_APPLY','SHOP_EXIT','SHOP_BUY_BLOCKED','SHOP_ROLL_BLOCKED'].includes(e.type)) lines.push(`第${e.round||0}回合 #${e.step} ${renderEvent(e)}`); }
 const triggerLines=buildTraceFromChanges(state.changes || []).filter(line=>/触发物体|modifier生效|外层战斗modifier/.test(line));
 if(triggerLines.length){ lines.push(''); lines.push('【触发链】'); for(const line of triggerLines.slice(-12)) lines.push(line); }
 if(Array.isArray(state.dayRouteRuns)&&state.dayRouteRuns.length){ lines.push(''); lines.push('【跨天成长】'); for(const run of state.dayRouteRuns.slice(-10)){ const economy=run.economy||{}; const construction=run.construction||{}; const build=construction.buildCore||{}; const goldFrom=Number.isFinite(economy.goldFrom)?economy.goldFrom:'?'; const goldTo=Number.isFinite(economy.goldTo)?economy.goldTo:'?'; lines.push(`Day${run.day}: 金币${goldFrom}→${goldTo}，背包${construction.inventoryCount ?? '?'}，遗物${construction.relicCount ?? '?'}，构筑=${build.summaryText || '尚未形成'}`); } }
 const buildCore=buildConstructionSummary(state);
 lines.push(''); lines.push('【最终状态】'); lines.push(`金币：${state.gold}`); lines.push(`构筑核心：${buildCore.summaryText}`); lines.push(`结果：${state.result ? state.result.code : '未结算'} / 评级：${state.result ? state.result.grade : '-'}`); if(state.shop.activeStall) lines.push(`当前摊位：${state.shop.activeStall.name} / ${state.shop.activeStall.tags.join('/')} / ${state.shop.activeStall.shopPoolId}`); if(state.shop.refreshState) lines.push(`刷新状态：免费${state.shop.refreshState.freeRolls} / 折扣${state.shop.refreshState.nextDiscount}% / 定向补货${state.shop.refreshState.targetedRestocks.length}`); lines.push(`背包：${state.inventory.map(inventoryText).join('、')}`); lines.push(`商店剩余：${(state.shop.offers||[]).map(offerText).join('、') || '空'}`); return lines.join('\n'); }
function renderShopReport(state){ const lines=[]; lines.push('《元素背包史》节点/商店链路报告'); for(const e of state.events.filter(e=>e.type.startsWith('SHOP') || e.type.startsWith('REWARD') || e.type.startsWith('NODE') || e.type.startsWith('BATTLE_OPTIONS') || e.type.startsWith('BATTLE_PICK') || e.type === 'ROUTE_BATTLE_OUTCOME' || e.type === 'ROUTE_REWARD_CLAIM')) lines.push(`#${e.step} ${e.text}`); if(state.shop.activeStall) lines.push(`摊位=${state.shop.activeStall.name} 标签=${state.shop.activeStall.tags.join('/')} 池=${state.shop.activeStall.shopPoolId}`); if(state.shop.refreshState) lines.push(`刷新状态=免费${state.shop.refreshState.freeRolls} 折扣${state.shop.refreshState.nextDiscount}% 定向补货${state.shop.refreshState.targetedRestocks.length}`); lines.push(`金币=${state.gold}`); return lines.join('\n'); }
module.exports={ renderPlayerReport, renderShopReport };
