const SUPPORTED_MECHANICS = new Set([
'none','mech_shield_flat','mech_armor_flat','mech_damage_reduce_pct','mech_first_hit_immunity','mech_damage_cap_per_round','mech_shield_regen','mech_thorn_shield','mech_element_barrier','mech_guard_taunt','mech_last_stand_shield','mech_counter_damage','mech_death_explosion','mech_self_destruct','mech_on_hit_blast','mech_reflect_first_hit','mech_shield_break_explosion','mech_retaliate_summon','mech_revenge_buff','mech_thorns_percent','mech_counter_attack','mech_grow_atk_each_round','mech_grow_shield_each_round','mech_rage_low_hp','mech_harden_when_hit','mech_soften_when_hit','mech_delayed_powerup','mech_consume_layers_grow','mech_enrage_after_round','mech_second_phase','mech_scale_with_allies','mech_summon_each_round','mech_death_summon','mech_split_into_minions','mech_summon_on_empty_cell','mech_copy_weak_self','mech_summon_wall','mech_summon_trap','mech_summon_when_hit','mech_summon_after_kill','mech_hatch_after_rounds','mech_fire_ignite_bonus','mech_water_heal_on_layer','mech_wind_push_on_hit','mech_earth_shield_on_layer','mech_multi_element_bonus','mech_trap_stack_trigger','mech_fire_cross_detonate_diamond','mech_water_cleanse_debuff','mech_wind_slow_ap','mech_earth_block_cell','mech_curse_gold_loss','mech_reduce_reward_if_alive','mech_castle_line_damage','mech_economy_decay_on_fail','mech_dirty_cell','mech_countdown_pressure','mech_shop_discount_after_clear','mech_bonus_reward_under_round5','mech_penalty_after_round10','mech_elite_reward_bonus'
]);
function getParam(unit, mech, key, fallback){ return (unit.mechanicParams && unit.mechanicParams[key] !== undefined) ? unit.mechanicParams[key] : (mech.defaultParams && mech.defaultParams[key] !== undefined ? mech.defaultParams[key] : fallback); }
function eachMechanic(unit, data, cb) { for (const id of (unit.mechanics || ['none'])) { const mech=data.mechanisms.find(m=>m.id===id); if (mech) cb(mech, id); } }
function applyBattleStart(state, unit){ eachMechanic(unit, state.data, (m,id)=>{ if(id==='mech_shield_flat'){ const shield=Number(getParam(unit,m,'shield',6)); unit.shield += shield; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'battle_start', mechanicId:id, unitId:unit.id, text:`${unit.name} 获得${shield}点开场护盾。`}); } }); }
function applyRoundStart(state, unit){ eachMechanic(unit, state.data, (m,id)=>{ if(id==='mech_shield_regen'||id==='mech_grow_shield_each_round'){ const shield=Number(getParam(unit,m,'shield', id==='mech_grow_shield_each_round'?2:3)); unit.shield += shield; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'round_start', mechanicId:id, unitId:unit.id, text:`${unit.name} 回合开始获得${shield}盾。`}); }
 if(id==='mech_grow_atk_each_round'||id==='mech_enrage_after_round'||id==='mech_delayed_powerup'){ const atk=Number(getParam(unit,m,'atk',1)); if(id==='mech_delayed_powerup' && state.round < Number(getParam(unit,m,'round',3))) return; unit.atk += atk; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'round_start', mechanicId:id, unitId:unit.id, text:`${unit.name} 攻击+${atk}。`}); }
 }); }
function beforeDamage(state, target, source, damage, ctx={}){ let final=Math.max(0, damage); const logs=[]; eachMechanic(target, state.data, (m,id)=>{ if(final<=0) return; if(id==='mech_armor_flat'){ const armor=Number(getParam(target,m,'armor',2)); final=Math.max(0, final-armor); logs.push(`${target.name} 护甲抵消${armor}。`); }
 if(id==='mech_damage_reduce_pct'){ const rate=Number(getParam(target,m,'rate',0.3)); const min=Number(getParam(target,m,'min_damage',1)); final=Math.max(min, Math.ceil(final*(1-rate))); logs.push(`${target.name} 百分比免伤，伤害降为${final}。`); }
 if(id==='mech_first_hit_immunity' && !target.flags.firstHitImmunityUsed){ target.flags.firstHitImmunityUsed=true; final=0; logs.push(`${target.name} 首次免疫，抵消本次伤害。`); }
 if(id==='mech_damage_cap_per_round'){ const cap=Number(getParam(target,m,'cap',8)); const used=target.roundDamageTaken||0; const allow=Math.max(0, cap-used); if(final>allow){ final=allow; logs.push(`${target.name} 本回合损血上限剩余${allow}。`); } }
 if(id==='mech_element_barrier' && ctx.element !== target.element){ const reduce=Number(getParam(target,m,'reduce',3)); final=Math.max(0, final-reduce); logs.push(`${target.name} 元素屏障抵消${reduce}。`); }
 });
 return { damage: final, logs };
}
function afterDamage(state, target, source, amount){ eachMechanic(target, state.data, (m,id)=>{ if(id==='mech_last_stand_shield' && !target.flags.lastStand && target.hp>0 && target.hp <= Math.ceil(target.maxHp*0.3)){ const shield=Number(getParam(target,m,'shield',8)); target.flags.lastStand=true; target.shield += shield; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_damage', mechanicId:id, unitId:target.id, text:`${target.name} 残血触发护盾+${shield}。`}); }
 if(id==='mech_rage_low_hp' && !target.flags.raged && target.hp>0 && target.hp <= Math.ceil(target.maxHp*0.5)){ target.flags.raged=true; target.atk += Number(getParam(target,m,'atk',2)); state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_damage', mechanicId:id, unitId:target.id, text:`${target.name} 低血狂怒。`}); }
 if(id==='mech_second_phase' && !target.flags.phase2 && target.hp>0 && target.hp <= Math.ceil(target.maxHp*0.5)){ target.flags.phase2=true; target.atk += 1; target.shield += 3; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_damage', mechanicId:id, unitId:target.id, text:`${target.name} 进入第二阶段。`}); }
 }); }
function afterHit(state, target, source, amount){ eachMechanic(target, state.data, (m,id)=>{ if(!source || amount<=0) return; if(id==='mech_counter_damage'||id==='mech_thorn_shield'||id==='mech_thorns_percent'||id==='mech_reflect_first_hit'){ if(id==='mech_reflect_first_hit' && target.flags.reflectUsed) return; if(id==='mech_reflect_first_hit') target.flags.reflectUsed=true; const reflect=id==='mech_thorns_percent'?Math.ceil(amount*0.5):Number(getParam(target,m,'reflect',2)); source.hp=Math.max(0, source.hp-reflect); state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_hit', mechanicId:id, unitId:target.id, targetId:source.id, text:`${target.name} 反伤${reflect}给${source.name}。`}); }
 if(id==='mech_harden_when_hit'){ target.def += 1; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_hit', mechanicId:id, unitId:target.id, text:`${target.name} 受击后防御+1。`}); }
 if(id==='mech_soften_when_hit'){ target.def = Math.max(0, target.def-1); state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_hit', mechanicId:id, unitId:target.id, text:`${target.name} 受击后防御-1。`}); }
 }); }
function onDeath(state, unit, source){ eachMechanic(unit, state.data, (m,id)=>{ if(id==='mech_death_explosion'||id==='mech_self_destruct'||id==='mech_shield_break_explosion'){ state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'on_death', mechanicId:id, unitId:unit.id, text:`${unit.name} 死亡爆发被记录，范围伤害进入事件流。`}); }
 if(id==='mech_death_summon'||id==='mech_split_into_minions'){ state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'on_death', mechanicId:id, unitId:unit.id, text:`${unit.name} 死亡召唤/分裂被记录。`}); }
 }); }
function afterElementApply(state, caster, target, element, layers){ eachMechanic(caster, state.data, (m,id)=>{ if(id==='mech_water_heal_on_layer' && element==='水'){ caster.hp=Math.min(caster.maxHp, caster.hp+layers); state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_element_apply', mechanicId:id, unitId:caster.id, text:`${caster.name} 施加水层后回复${layers}。`}); }
 if(id==='mech_earth_shield_on_layer' && element==='土'){ caster.shield+=layers; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_element_apply', mechanicId:id, unitId:caster.id, text:`${caster.name} 施加土层后护盾+${layers}。`}); }
 if(['mech_summon_on_empty_cell','mech_summon_trap','mech_dirty_cell','mech_earth_block_cell'].includes(id)){ state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'after_element_apply', mechanicId:id, unitId:caster.id, text:`${caster.name} 触发${m.name}，已写入事件流。`}); }
 }); }
function battleEndMechanics(state, result){ for (const u of state.units){ if(!u.alive) continue; eachMechanic(u,state.data,(m,id)=>{ if(id==='mech_shop_discount_after_clear' && result.win){ state.shop.nextDiscount = Math.max(state.shop.nextDiscount || 0, 50); state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'battle_end', mechanicId:id, unitId:u.id, text:`${u.name} 让下一商店获得50%折扣。`}); }
 if(id==='mech_bonus_reward_under_round5' && result.win && state.round<=5){ result.gold += 1; state.events.push({step:state.nextStep++, phase:state.phase, round:state.round, type:'MECHANIC_APPLIED', hook:'battle_end', mechanicId:id, unitId:u.id, text:`${u.name} 触发快速奖励+1金币。`}); }
 if(id==='mech_curse_gold_loss'){ result.gold = Math.max(0,result.gold-1); }
 }); }
}
module.exports = { SUPPORTED_MECHANICS, applyBattleStart, applyRoundStart, beforeDamage, afterDamage, afterHit, onDeath, afterElementApply, battleEndMechanics };
