const PUBLIC_COMMANDS = Object.freeze([
  'START_BATTLE',
  'START_NEXT_ROUND',
  'SELECT_HERO',
  'SELECT_UNIT',
  'SELECT_CELL',
  'SELECT_SLOT',
  'SET_ACTION_DIRECTION',
  'SET_SLOT_DIR',
  'MOVE_HERO',
  'AUTO_POSITION_HEROES',
  'USE_SLOT',
  'USE_ACTION_SLOT',
  'RUN_PLAYER_ALL_OUT',
  'END_PLAYER_TURN',
  'RUN_MONSTER_TURN',
  'BUILD_PREVIEW',
  'GET_CELL_DETAIL',
  'RUN_BATTLE',
  'GENERATE_NODE_OPTIONS',
  'PICK_NODE',
  'GENERATE_BATTLE_OPTIONS',
  'PICK_BATTLE_ENCOUNTER',
  'RUN_ROUTE_FIXED_BATTLE',
  'CLAIM_ROUTE_REWARD',
  'REWARD_OPTIONS',
  'PICK_REWARD',
  'ENTER_SHOP',
  'ROLL_SHOP',
  'FREEZE_OFFER',
  'UNFREEZE_OFFER',
  'BUY_OFFER',
  'APPLY_SHOP_EVENT',
  'EXIT_SHOP',
  'RUN_FULL_DAY',
  'RUN_FULL_RUN',
  'SELL_UNIT',
  'TOGGLE_UNIT_ACTIVE',
  'EXPORT_BATTLE_TRACE',
  'REPLAY_BATTLE_TRACE',
  'EXPORT_REPLAY',
  'SETUP_DAY7_FIRE_TRIAL',
  'RUN_DAY7_FIRE_TURN_1',
  'RUN_DAY7_FIRE_TRIAL_ALL'
]);

const ACTION_ALIASES = Object.freeze({
  runBattle: 'RUN_BATTLE',
  generateNodeOptions: 'GENERATE_NODE_OPTIONS',
  pickNode: 'PICK_NODE',
  generateBattleOptions: 'GENERATE_BATTLE_OPTIONS',
  pickBattleEncounter: 'PICK_BATTLE_ENCOUNTER',
  runRouteFixedBattle: 'RUN_ROUTE_FIXED_BATTLE',
  claimRouteReward: 'CLAIM_ROUTE_REWARD',
  startBattle: 'START_BATTLE',
  startNextRound: 'START_NEXT_ROUND',
  rewardOptions: 'REWARD_OPTIONS',
  pickReward: 'PICK_REWARD',
  enterShop: 'ENTER_SHOP',
  rollShop: 'ROLL_SHOP',
  freezeOffer: 'FREEZE_OFFER',
  unfreezeOffer: 'UNFREEZE_OFFER',
  buyOffer: 'BUY_OFFER',
  applyShopEvent: 'APPLY_SHOP_EVENT',
  exitShop: 'EXIT_SHOP',
  runFullDay: 'RUN_FULL_DAY',
  runFullPlayerDayFlow: 'RUN_FULL_DAY',
  runFullRun: 'RUN_FULL_RUN',
  sellUnit: 'SELL_UNIT',
  toggleUnitActive: 'TOGGLE_UNIT_ACTIVE',
  useActionSlot: 'USE_ACTION_SLOT',
  runPlayerAllOut: 'RUN_PLAYER_ALL_OUT',
  useSlot: 'USE_SLOT',
  selectUnit: 'SELECT_UNIT',
  selectHero: 'SELECT_HERO',
  selectCell: 'SELECT_CELL',
  selectSlot: 'SELECT_SLOT',
  setSlotDir: 'SET_SLOT_DIR',
  setActionDirection: 'SET_ACTION_DIRECTION',
  moveHero: 'MOVE_HERO',
  autoPositionHeroes: 'AUTO_POSITION_HEROES',
  endPlayerTurn: 'END_PLAYER_TURN',
  runMonsterTurn: 'RUN_MONSTER_TURN',
  buildPreview: 'BUILD_PREVIEW',
  getCellDetail: 'GET_CELL_DETAIL',
  exportBattleTrace: 'EXPORT_BATTLE_TRACE',
  replayBattleTrace: 'REPLAY_BATTLE_TRACE',
  exportReplay: 'EXPORT_REPLAY',
  setupDay7FireTrial: 'SETUP_DAY7_FIRE_TRIAL',
  runDay7FireTurn1: 'RUN_DAY7_FIRE_TURN_1',
  runDay7FireTrialAll: 'RUN_DAY7_FIRE_TRIAL_ALL'
});

module.exports = { PUBLIC_COMMANDS, ACTION_ALIASES };
